version: '3'

services:
    alpine:
        image: software_packages:alpine
        build: .
        ports:
            - 5000:8080
    
    ubuntu:
        image: software_packages:ubuntu
        build:
            context: .
            dockerfile: Dockerfile-ubuntu
        ports:
            - 5001:8080

